---
title: "TSL2 Hypothesis 3"
author: "A.G. Mitchell"
date: '2022-06-07'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##### Libraries #####
if (!require("pacman")) install.packages("pacman")
  pacman::p_load(boot, broom.mixed, car, caret, ggeffects, 
                 gghalves, ggpol, ggpubr, groupdata2, lme4, lmerTest, 
                 RColorBrewer, rcompanion,
                 reshape2, Rmisc, ROCR, rsample, tidyverse, wesanderson,
                 bayesplot, brms, cmdstanr, extraDistr, furrr)
```

# Getting data
```{r}
tsl_file <- file.path("data", "anonymised_tsl2_208.csv")
sum_file <- file.path("data", "summary_tsl2_208.csv")

# load all data file
if (file.exists(tsl_file)){
  tsl2 <- read.csv(tsl_file)
  } else {
    print('Data file does not exist, check data is in current directory.')
  }
# load data summary file
if (file.exists(sum_file)){
  sum_dat <- read.csv(sum_file)
  } else {
    print('Data file does not exist, check data is in current directory if not, run tsl2_phs_q1.Rmd first')
  }
```

Functions at the top
```{r}
# Zscore function
calc_z <- function (value) {
  z_score <- (value - mean(value))/sd(value)
}

# contrast function
# Calculating contrast
# TCF - thermal contrast function (developed by FF)

# the TCF assumes that maximum possible TSL temperature is 50deg
TCF <- function (Tmax, Tmin) {
  top_temp = 50
  contrast <- (Tmax - Tmin)/top_temp
}

#logistic function
prob_func = function(x,a,b,g,l){
  #a = intercept, b = slope (lower limit = 0), x = data
  #l = lapse rate[0 - 0.5], g = guess rate[0 - 0.5]
  
  prob_func = g + (1-g-l)*(brms::inv_logit_scaled(b*(x-a)))
  #prob_func = 0.5+0.5*erf((x-a)/(sqrt(2)*b))
  
  return(prob_func)
}
```

# Organise data and calculate contrast for each trial
# First innocuous thermal contrast
```{r}
# extract relevant trials (etc)
df <- tsl2 %>% 
  filter(task == "tsl2" & quality == 'cold',instruction == 'detect') %>% 
  select(c(exp_id,instruction,trial,baseline,threshold,phs,age,gender)) %>% 
  dplyr::rename(subject = exp_id,
         phs_01 = phs) %>% 
  drop_na() #move nas
# any value < 0 should = 0
df$threshold[df$threshold < 0] <- 0
  
# using the thermal contrast function:
  # (tmax - tmin)/max possible temp (50)
df_con <- df
baselineT <- 32 #temperature below which pp can detect change

# then calculate contrast from max temperature
df_con <- df_con %>% 
  mutate(TCF = TCF(baseline, threshold))

```

# try and fit PF to data
```{r}
df_con %>% filter(subject < 21) %>% 
  ggplot(aes(x = TCF, y = phs_01, colour = as_factor(subject))) +
  geom_point() +
  facet_wrap(~subject) +
  theme_classic() +
  theme(legend.position = 'none')

# stan model
stanHmodel1 <- cmdstanr::cmdstan_model('phs-hierarchical_p1.stan') #initiate model

# run
fit = stanHmodel1$sample(data = list(N = nrow(df_con), 
                                    tcf = (df_con$TCF)*100,
                                    phs = df_con$phs_01,
                                    S = length(unique(df_con$subject)),
                                    S_id = df_con$subject),
                        refresh = 200,
                        iter_sampling = 2000,
                        iter_warmup = 2000,
                        parallel_chains = 4,
                        max_treedepth = 12,
                        adapt_delta = 0.95,
                        init = 0)

fit$diagnostic_summary()
fit$summary(c('mus_phs','sigmas_phs'))
mcmc_trace(fit$draws(variables = c('mus_phs','sigmas_phs'))) #hairy caterpillars
```

# plot individual subject fits
```{r}
subject_draws = as_draws_df(fit$draws(c("mus_phs","sigmas_phs","difs_phs"))) %>% 
                select(-contains("."))

#get 200 random ids for the draws we select to plot.
draw_id = sample(1:4000,20)

params = subject_draws %>% 
  mutate(draw = 1:n()) %>% 
  filter(draw %in% draw_id) %>% 
  pivot_longer(
    cols = starts_with("difs"),
    names_to = c("outcome","parameters","id"),
    names_pattern = "difs_([a-z]+)\\[(\\d+),(\\d+)\\]"
  ) 

# create dataframe for each outcome variable
params_phs = params %>%   
  filter(outcome == 'phs') %>% 
  pivot_wider(names_from = "parameters", values_from = value) %>% 
  dplyr::rename("a" = "1", "b" = "2", "g" = "3", "l" = "4") %>% 
  mutate(a_phs = exp(`mus_phs[1]` + a * `sigmas_phs[1]`),
         b_phs = exp(`mus_phs[2]` + b * `sigmas_phs[2]`),
         g_phs = inv_logit_scaled(`mus_phs[3]` + g * `sigmas_phs[3]`)/2,
         l_phs = inv_logit_scaled(`mus_phs[4]` + l * `sigmas_phs[4]`)/2)

params_phs = params_phs %>% 
  mutate(x = list(seq(min(df_con$TCF),max(df_con$TCF),length.out = 50)*100)) %>% 
  unnest(x) %>% 
  rowwise() %>% 
  mutate(p = prob_func(x,a_phs,b_phs,g_phs,l_phs))
```

```{r}
params_phs %>% 
  filter(as.numeric(id)>=20 & as.numeric(id)<40) %>% 
  ggplot()+
  geom_point(data = df_con %>% filter(as.numeric(id)>=20 & as.numeric(id)<40),
             aes(x = TCF*100, y = phs_01))+
  geom_line(aes(x,p,group=draw),alpha=.5)+
  facet_wrap(~id)+
  theme_classic()
```


